# Generated by Django 3.1.7 on 2021-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Attendance', '0004_auto_20210301_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='presence',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
