# Generated by Django 3.1.7 on 2021-03-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='fathers_nid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mothers_nid',
            field=models.IntegerField(),
        ),
    ]
